using Artexacta.App.Seguimiento;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Seguimiento_SeguimientoCampana : System.Web.UI.Page
{
    private static List<string> semanas = new List<string>();
    private static List<Video> videos = new List<Video>();
    private static List<KPICampana> kpis = new List<KPICampana>();

    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
            CargarInfo();
    }

    private void CargarInfo()
    {
        //Inicializamos las semanas
        for (int i = 1; i < 53; i++)
        {
            semanas.Add(i + "");
        }
        SemanaComboBox.DataSource = semanas;
        SemanaComboBox.DataBind();
        //Inicializamos Videos
        videos.Add(new Video(1, "https://www.youtube.com/embed/GME7F146d4s"));
        videos.Add(new Video(2, "https://www.youtube.com/embed/fX9yv5z1MQA"));
        videos.Add(new Video(3, "https://www.youtube.com/embed/vYWF1hkvYKI"));

        CampanaComboBox.DataSource = videos;
        CampanaComboBox.DataTextField = "nombreCombo";
        CampanaComboBox.DataValueField = "idCampana";
        CampanaComboBox.DataBind();
        #region Datos KPIs Semana 1
        //Inicializamos KPIs x campaña (1)
        KPICampana kpi = new KPICampana(1, 1);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 0, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 0, 43));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 0, 65));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 0, 10));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 0, 57));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 2);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 34, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 43, 25));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 65, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 10, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 57, 60));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 3);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 4);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 5);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 6);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 7);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 8);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 9);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 10);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 11);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 12);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 13);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 14);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 15);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 16);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 17);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 18);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 19);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 20);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(1, 23);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(1, 24);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 25);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 26);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 27);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 28);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 29);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 30);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 31);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 32);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 33);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 34);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 35);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 36);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 37);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 38);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 39);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 40);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 41);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 42);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 43);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 44);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 45);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 46);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 47);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 48);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 49);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 50);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 51);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(1, 52);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        #endregion
        #region Datos KPIs Semana 2
        //Inicializamos KPIs x campaña (2)
        kpi = new KPICampana(2, 1);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 0, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 0, 43));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 0, 65));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 0, 10));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 0, 57));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 2);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 34, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 43, 25));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 65, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 10, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 57, 60));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 3);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 4);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 5);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 6);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 7);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 8);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 9);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 10);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 11);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 12);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 13);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 14);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 15);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 16);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 17);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 18);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 19);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 20);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(2, 23);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(2, 24);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 25);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 26);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 27);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 28);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 29);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 30);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 31);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 32);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 33);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 34);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 35);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 36);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 37);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 38);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 39);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 40);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 41);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 42);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 43);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 44);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 45);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 46);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 47);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 48);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 49);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 50);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 51);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(2, 52);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
#endregion
        #region Datos KPIs Semana 3
        //Inicializamos KPIs x campaña (3)
        kpi = new KPICampana(3, 1);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 0, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 0, 43));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 0, 65));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 0, 10));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 0, 57));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 2);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 34, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 43, 25));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 65, 64));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 10, 34));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 57, 60));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 3);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 4);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 5);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 6);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 7);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 8);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 9);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 10);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 11);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 12);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 13);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 14);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 15);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 16);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 17);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 18);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 19);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 20);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 21);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(3, 23);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpi = new KPICampana(3, 24);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 25);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 26);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 27);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 28);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 29);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 30);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 31);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 32);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 33);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 34);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 35);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 36);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 37);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 38);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 39);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 40);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 41);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 42);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 43);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 44);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 45);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 46);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 47);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 48);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 49);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 50);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 51);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        kpi = new KPICampana(3, 52);
        kpi.valoresKPIs.Add(new KPIDetalle("Spontaneous Message Recall", 1, 64, 55));
        kpi.valoresKPIs.Add(new KPIDetalle("Ad Aworeness", 2, 25, 38));
        kpi.valoresKPIs.Add(new KPIDetalle("Brand Recognition", 3, 64, 70));
        kpi.valoresKPIs.Add(new KPIDetalle("Aided Message Recall", 4, 34, 50));
        kpi.valoresKPIs.Add(new KPIDetalle("Likins", 5, 60, 61));
        kpis.Add(kpi);
        #endregion

        videoFrame.Text = "<iframe width=\"420\" height=\"315\" src=\"" + videos[0].urlVideo + "\" frameborder=\"0\" allowfullscreen></iframe>";
        KPIRepeater.DataSource = kpis[0].valoresKPIs;
        KPIRepeater.DataBind();
    }

    protected void CampanaComboBox_SelectedIndexChanged(object sender, EventArgs e)
    {
        int semana = Convert.ToInt32(SemanaComboBox.SelectedValue);
        int indiceVideo = Convert.ToInt32(CampanaComboBox.SelectedValue);
        videoFrame.Text = "<iframe class=\"embed-responsive-item\" width=\"420\" height=\"315\" src=\"" + videos[indiceVideo - 1].urlVideo + "\" frameborder=\"0\" allowfullscreen></iframe>";
        foreach (KPICampana item in kpis)
        {
            if (semana == item.semana && indiceVideo == item.idCampana)
            {
                KPIRepeater.DataSource = item.valoresKPIs;
                KPIRepeater.DataBind();
            }
        }
    }
    protected void SemanaComboBox_SelectedIndexChanged(object sender, EventArgs e)
    {
        int semana = Convert.ToInt32(SemanaComboBox.SelectedValue);
        int indiceVideo = Convert.ToInt32(CampanaComboBox.SelectedValue);

        foreach (KPICampana item in kpis)
        {
            if (semana == item.semana && indiceVideo == item.idCampana)
            {
                KPIRepeater.DataSource = item.valoresKPIs;
                KPIRepeater.DataBind();
            }
        }
    }
}